name: Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Setup
      run: python3 -m pip install -r requirements-dev.txt
    - name: Build
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  github-release:
    runs-on: ubuntu-latest

    needs:
    - build

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: SebRollen/toml-action@v1.2.0
      id: read_toml
      with:
        file: 'pyproject.toml'
        field: 'project.version'
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      continue-on-error: true
      run: >-
        gh release create
        "loom-${{ steps.read_toml.outputs.value }}"
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        "loom-${{ steps.read_toml.outputs.value }}" dist/**
        --repo '${{ github.repository }}'
        --clobber
